name: Test

on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]

jobs:
    unit-test:
        runs-on: ubuntu-latest
        container: reactnativecommunity/react-native-android

        steps:
            - uses: actions/checkout@v2

            - name: Envinfo
              run: npx envinfo

            - name: Install yarn dependencies
              run: yarn install

            - name: Gradlew test
              run: cd android && chmod +x gradlew && ./gradlew test

            - name: Jest
              run: yarn jest
